version: '3.4'

services:
  db:
    image: mysql:5.7.22
    command: mysql --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    volumes:
      - type: bind
        source: ./DbBackup/backup.sql
        target: /docker-entrypoint-initdb.d/backup.sql
    ports:
      - "3306:3306"
    networks:
      - udemy-network

  restwithaspnetudemy:
    image: restwithaspnetudemy-api
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile

    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
    networks:
      - udemy-network

networks:
  udemy-network:
    driver: bridge
